### PR TITLE
Escape - character so regex works on PHP 7.3

### LINKED ISSUE #250: PHP 7.3 - preg_replace(): Compilation failed: invalid range in character class at offset 24
When using PHP 7.3 I get the error:
`preg_replace(): Compilation failed: invalid range in character class at offset 24`

It seems to be an issue in `Twitter.php` with the hashtag regex. 

```php
$patterns['hashtag'] = '(?:(?<=\s)|^)#(\w*[\p{L}-\d\p{Cyrillic}\d]+\w*)';
...
// Hashtag
$text = preg_replace('/'.$patterns['hashtag'].'/ui', '<a href="https://twitter.com/search?q=%23\\1" target="_blank">#\\1</a>', $text);
```

You can see example output for different versions of PHP at: https://3v4l.org/H56I0

### PR DESCRIPTION
**Pull request by ejunker**
Fixes #250 

On PHP 7.3 it was giving a warning `preg_replace(): Compilation failed: invalid range in character class at offset 24`

### CODE REVIEW

**Comment by neoighodaro** [comment]
Hey guys, is this PR going to be merged sometime soon? It's been months.

**Comment by atymic** [comment]
Hey :)

We've merged a PR to fix this in our fork
https://github.com/atymic/laravel-twitter

More Info:

I've created a fork (with issues enabled) & packagist release of the current version in the same namespace (unlike some of the other forks).

I plan to maintain this fork as i'm using it in a few projects.

https://github.com/atymic/laravel-twitter

I'd love to work with others on the package as well, so feel free to reach out.

If the original author does return, I'd be happy to merge our changes back into the mainline. If not, I plan to release v3 in a different namespace and fix a lot of the pre existing issues.

**Comment by atymic** [comment]
Closed in favour of #270

**Comment by atymic** [comment]
This will be tagged shortly.
